### ISSUE TITLE
[gopls] not work for windows

### ISSUE THREAD

**Issue by gukz** [williamboman/nvim-lsp-installer#262]
**Describe the bug**
A clear and concise description of what the bug is and why you think it's an issue with nvim-lsp-installer.
When I use the latest plugin version, and I am writing go project, I found the installed gopls cannot integrate with neovim.
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12511562/141760358-3eacbe10-aa2d-40f0-87e0-3a1b1cf88ffd.png)

**System info (please complete the following information):**
 - OS: [windows 10]
 - Neovim version: 0.6.0

Please also include any other system information you think is relevant!

**error log**
c:...\AppData\Local\Temp\nvim\lsp.log
```
[ START ] 2021-11-15T17:37:17+0800 ] LSP logging initiated
[ ERROR ] 2021-11-15T17:37:24+0800 ] ...Files\Neovim\share\nvim\runtime\lua\vim\lsp\handlers.lua:423 ]	"2021/11/15 17:37:24 proj/app/openapi: no dep handle for proj/gen/models: no metadata for proj/gen/models\n\tsnapshot=0\n"
[ ERROR ] 2021-11-15T17:37:44+0800 ] ...gram Files\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:462 ]	"rpc"	"C:\\dev\\nvim\\nvim-data\\lsp_servers\\go\\gopls"	"stderr"	'panic: only file URIs are supported, got "c" from "C:\\\\dev\\\\proj\\\\app\\\\openapi\\\\handlers.go"\n\ngoroutine 7691 [running]:\n'
[ ERROR ] 2021-11-15T17:37:44+0800 ] ...gram Files\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:462 ]	"rpc"	"C:\\dev\\nvim\\nvim-data\\lsp_servers\\go\\gopls"	"stderr"	"golang.org/x/tools/internal/span.URI.Filename({0xc0099c0420, 0x23})\n\tC:/dev/nvim/nvim-data/lsp_servers/gopls.tmp/pkg/mod/golang.org/x/tools@v0.1.8-0.20211014194737-fc98fb2abd48/internal/span/uri.go:32 +0x65\ngolang.org/x/tools/internal/lsp.(*Server).definition(0xc009a83078, {0x1130418, 0xc00cb8c140}, 0xc003daf540)\n\tC:/dev/nvim/nvim-data/lsp_servers/gopls.tmp/pkg/mod/golang.org/x/tools@v0.1.8-0.20211014194737-fc98fb2abd48/internal/lsp/definition.go:16 +0x92\ngolang.org/x/tools/internal/lsp.(*Server).Definition(0xc009a28150, {0x1130418, 0xc00cb8c140}, 0xdbbb20)\n\tC:/dev/nvim/nvim-data/lsp_servers/gopls.tmp/pkg/mod/golang.org/x/tools@v0.1.8-0.20211014194737-fc98fb2abd48/internal/lsp/server_gen.go:40 +0x25\ngolang.org/x/tools/internal/lsp/protocol.serverDispatch({0x1130418, 0xc00cb8c140}, {0x115e920, 0xc0000b1320}, 0xc008f6c000, {0x1130680, 0xc00cb8c000})\n\tC:/dev/nvim/nvim-data/lsp_servers/gopls.tmp/pkg/mod/golang.org/x/tools@v0.1.8-0.20211014194737-fc98fb2abd48/internal/lsp/protocol/tsserver.go:410 +0x19fc\ngolang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0x1130418, 0xc00cb8c140}, 0xc008f6c000, {0x1130680, 0xc00cb8c000})\n\tC:/dev/nvim/nvim-data/lsp_servers/gopls.tmp/pkg/mod/golang.org/x/tools@v0.1.8-0.20211014194737-fc98fb2abd48/internal/lsp/protocol/protocol.go:154 +0x90\ngolang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0x1130418, 0xc00cb8c140}, 0xc008f6c000, {0x1130680, 0xc00cb8c000})\n\tC:/dev/nvim/nvim-data/lsp_servers/gopls.tmp/pkg/mod/golang.org/x/tools@v0.1.8-0.20211014194737-fc98fb2abd48/internal/lsp/lsprpc/lsprpc.go:506 +0xa7d\ngolang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x1130418, 0xc00cb8c140}, 0xc00e934408, {0x1130680, 0xc00cb8c000})\n\tC:/dev/nvim/nvim-data/lsp_servers/gopls.tmp/pkg/mod/golang.org/x/tools@v0.1.8-0.20211014194737-fc98fb2abd48/internal/jsonrpc2/handler.go:35 +0xf6\ngolang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()\n\tC:/dev/nvim/nvim-data/lsp_servers/gopls.tmp/pkg/mod/golang.org/x/tools@v0.1.8-0.20211014194737-fc98fb2abd48/internal/jsonrpc2/handler.go:103 +0xa3\ncreated by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1\n\tC:/dev/nvim/nvim-data/lsp_servers/gopls.tmp/pkg/mod/golang.org/x/tools@v0.1.8-0.20211014194737-fc98fb2abd48/internal/jsonrpc2/handler.go:100 +0x20f\n"
```

this make gopls unusable in windows

**Comment by williamboman** [comment]
Hi! It seems like gopls is being successfully installed, which is where the responsibilities of this plugin ends. I'm not sure what could be going wrong, but I'd suggest creating an issue in https://github.com/neovim/nvim-lspconfig/issues instead, they'd be able to point you in the right direction
