### ISSUE TITLE
Client 1 quit with exit code 1 and signal 0 (html, css)

### ISSUE THREAD

**Issue by wthollingsworth** [williamboman/nvim-lsp-installer#325]
**Describe the bug**
Trying out html and css servers, but they both error out when opening files.

**Expected behavior**
That the language servers would start.

**System info (please complete the following information):**

-   OS: Pop_OS! 21.04
-   Neovim version: 0.6.0

Checkhealth output (`:checkhealth nvim-lsp-installer`):

Not sure what's up with it saying Python and Plain sh aren't installed.  I've got both.

```
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - ERROR: **Composer**: not installed
  - ERROR: **PHP**: not installed
  - ERROR: **python**: not installed
  - ERROR: **sh**: not installed
  - INFO: **bash**: `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`
  - INFO: **tar**: `tar (GNU tar) 1.34`
  - INFO: **gzip**: ``
  - INFO: **wget**: `GNU Wget 1.21 built on linux-gnu.`
  - INFO: **python3**: `Python 3.9.5`
  - INFO: **node**: `v12.21.0`
  - INFO: **Ruby**: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]`
  - INFO: **Go**: `go version go1.16.2 linux/amd64`
  - INFO: **curl**: `curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.43.0 librtmp/2.3`
  - INFO: **RubyGem**: `3.2.5`
  - INFO: **java**: `javac 11.0.11`
  - INFO: **npm**: `8.3.0`
```

**LSP log**
```
[ERROR][2021-12-10 20:10:39] .../vim/lsp/rpc.lua:417	"rpc"	"/home/drwhattheheck/.local/share/nvim/lsp_servers/cssls/node_modules/.bin/vscode-css-language-server"	"stderr"	"/home/drwhattheheck/.local/share/nvim/lsp_servers/cssls/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return this._head?.value;\n                          ^\n\nSyntaxError: Unexpected token '.'\n    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module._compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/home/drwhattheheck/.local/share/nvim/lsp_servers/cssls/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n"

[ERROR][2021-12-10 20:20:45] .../vim/lsp/rpc.lua:417	"rpc"	"/home/drwhattheheck/.local/share/nvim/lsp_servers/html/node_modules/.bin/vscode-html-language-server"	"stderr"	"/home/drwhattheheck/.local/share/nvim/lsp_servers/html/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return this._head?.value;\n                          ^\n\nSyntaxError: Unexpected token '.'\n    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module._compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/home/drwhattheheck/.local/share/nvim/lsp_servers/html/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n"
```

**Install log**

```

[INFO  Fri 10 Dec 2021 07:26:58 PM EST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:579: Installation completed server_name="cssls", success=true
[INFO  Fri 10 Dec 2021 08:04:54 PM EST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:579: Installation completed server_name="html", success=true
```

Maybe something on my end and not a bug, but I'd really appreciate any thoughts or help.

**Comment by williamboman** [comment]
Hey! Your Node version seems a bit out of date. Generally, being on an LTS version is good enough but this all depends on each individual server's requirements.

**Comment by wthollingsworth** [comment]
Oof, not sure how I managed that, but everything looks good now.  Thanks!
