### ISSUE TITLE
New configuration breaks other servers

### ISSUE THREAD

**Issue by bmulholland** [williamboman/nvim-lsp-installer#641]
### Problem description

I have two LSP servers (solargraph and sorbet) that I manage the install of manually because they use gems installed in my application, not globally. Switching to the new setup config breaks those.

### Neovim version (>= 0.6)

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin spork.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

solargraph, sorbet

### Actual behavior

When I use the new `require("nvim-lsp-installer").setup({})`, those servers won't run anymore.

The LSP log says:

```
[START][2022-04-29 15:16:15] LSP logging initiated
[ERROR][2022-04-29 15:16:16] .../vim/lsp/rpc.lua:420	"rpc"	"srb"	"stderr"	"/Users/bmulholland/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem sorbet (>= 0.a) with executable srb (Gem::GemNotFoundException)\n"
[ERROR][2022-04-29 15:16:16] .../vim/lsp/rpc.lua:420	"rpc"	"srb"	"stderr"	"\tfrom /Users/bmulholland/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems.rb:284:in `activate_bin_path'\n\tfrom /Users/bmulholland/.rvm/gems/ruby-3.1.2@recital-backend/bin/srb:25:in `<main>'\n"
[ERROR][2022-04-29 15:16:16] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"/Users/bmulholland/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem solargraph (>= 0.a) with executable solargraph (Gem::GemNotFoundException)\n\tfrom /Users/bmulholland/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems.rb:284:in `activate_bin_path'\n"
[ERROR][2022-04-29 15:16:16] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"\tfrom /Users/bmulholland/.rvm/gems/ruby-3.1.2@recital-backend/bin/solargraph:25:in `<main>'\n\tfrom /Users/bmulholland/.rvm/gems/ruby-3.1.2@recital-backend/bin/ruby_executable_hooks:22:in `eval'\n\tfrom /Users/bmulholland/.rvm/gems/ruby-3.1.2@recital-backend/bin/ruby_executable_hooks:22:in `<main>'\n"
```

### Expected behavior

Unrelated LSPs run without lsp-installer changing anything.

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: Composer: not available
  - WARNING: PHP: not available
  - WARNING: julia: not available
  - OK: bash: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: tar: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: gzip: `Apple gzip 353.100.22`
  - OK: curl: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.5 zlib/1.2.      11 nghttp2/1.45.1`
  - OK: python3: `Python 3.9.12`
  - OK: node: `v18.0.0`
  - OK: Ruby: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]`
  - OK: sh: `Ok`
  - OK: wget: `GNU Wget 1.21.3 built on darwin21.3.0.`
  - OK: cargo: `cargo 1.59.0 (49d8809dc 2022-02-10)`
  - OK: java: `Ok`
  - OK: Go: `go version go1.18.1 darwin/arm64`
  - OK: npm: `8.8.0`
  - OK: pip3: `pip 22.0.4 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: RubyGem: `3.3.7`
  - OK: javac: `javac 17.0.3`
```

**Comment by williamboman** [comment]
Ah. I had a feeling this approach was being too intrusive. I've pushed a semi-fix (https://github.com/williamboman/nvim-lsp-installer/commit/5ea43223f03db07ea9951c62d6d66e8ca8319412) that avoids applying config changes for servers that aren't installed at the point of setup. I'll have to think about it a bit more.
