### ISSUE TITLE
grammarly error

### ISSUE THREAD

**Issue by 0xRZ** [williamboman/nvim-lsp-installer#712]
### Problem description

grammarly-languageserver is unusable

### Why do you think this is an issue with nvim-lsp-installer?

Not sure whether it is nvim-lsp-installer specific issue since i haven't managed to run standalone upstream LSP binary as well

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+32-gf4f593b33
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

linux opensuse

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

grammarly-languageserver

### Steps to reproduce

`init.vim` i tested with:
```vim
let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
	execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

call plug#begin(s:plug_dir)
Plug 'neovim/nvim-lspconfig'
Plug 'williamboman/nvim-lsp-installer'
call plug#end()
PlugInstall | quit

lua << EOF
require("nvim-lsp-installer").setup {
	automatic_installation = false,
	ensure_installed = { "grammarly", },
}
local lsp_conf = require'lspconfig'

lsp_conf.grammarly.setup {}

EOF
```
Whenever i open any markdown file, LSP fails with:
```
Client 1 quit with exit code 1 and signal 0
Press ENTER or type command to continue
```

### Actual behavior

Grammarly lsp always exits with error.

### Expected behavior

Grammarly lsp started succesfully

### LspInfo

```shell
Language client log: /home/user/.cache/nvim/lsp.log
Detected filetype:   markdown

0 client(s) attached to this buffer:

Other clients that match the filetype: markdown

Config: grammarly
filetypes:         markdown
root directory:    NA
cmd:               unofficial-grammarly-language-server --stdio
cmd is executable: true (checked by nvim-lsp-installer)
autostart:         true
custom handlers:   $/updateDocumentState

Configured servers list: grammarly
```
```


### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: Composer: not available
  - WARNING: PHP: not available
  - WARNING: javac: not available
  - WARNING: julia: not available
  - OK: bash: `GNU bash, version 5.1.16(1)-release (x86_64-suse-linux)`
  - OK: gzip: `gzip 1.11`
  - OK: wget: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: python3: `Python 3.8.12`
  - OK: node: `v16.14.2`
  - OK: Go: `go version go1.17.8 linux/amd64`
  - OK: sh: `Ok`
  - OK: tar: `tar (GNU tar) 1.34`
  - OK: cargo: `cargo 1.59.0`
  - OK: npm: `8.5.0`
  - OK: curl: `curl 7.81.0 (x86_64-suse-linux-gnu) libcurl/7.81.0 OpenSSL/1.1.1m-fips zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/      0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.46.0 OpenLDAP/2.4.59`
  - OK: Ruby: `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-gnu]`
  - OK: java: `Ok`
  - OK: RubyGem: `3.3.7`
  - OK: pip3: `pip 22.0.4 from /home/user/.local/lib/python3.8/site-packages/pip (python 3.8)`
  - OK: GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Sat 21 May 2022 07:44:57 PM MSK.
```
```


### Screenshots or recordings

_No response_

**Comment by williamboman** [comment]
Hello! Can you find anything of interest in `:LspLog`? I see in the `:LspInfo` that lspconfig was unable to find a project root (`root directory: NA`), in which case the server won't be started (see `:h lspconfig-root-dir`)

**Comment by 0xRZ** [comment]
@williamboman 
`:LspLog` is

```
[START][2022-05-25 16:59:04] LSP logging initiated
[WARN][2022-05-25 16:59:04] .../lua/vim/lsp.lua:840	"server_request: no handler found for"	"$/getToken"
[ERROR][2022-05-25 16:59:04] .../vim/lsp/rpc.lua:430	"rpc"	"unofficial-grammarly-language-server"	"stderr"	"ResponseError: MethodNotFound\n    at handleResponse (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/common/connection.js:512:48)\n    at processMessageQueue (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/common/connection.js:308:17)\n    at Immediate.<anonymous> (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/common/connection.js:292:13)\n    at processImmediate (node:internal/timers:466:21) {\n  code: -32601,\n  data: undefined\n}\n"
[WARN][2022-05-25 16:59:04] .../lua/vim/lsp.lua:840	"server_request: no handler found for"	"$/getCredentials"
[ERROR][2022-05-25 16:59:04] .../vim/lsp/rpc.lua:430	"rpc"	"unofficial-grammarly-language-server"	"stderr"	"ResponseError: MethodNotFound\n    at handleResponse (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/common/connection.js:512:48)\n    at processMessageQueue (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/common/connection.js:308:17)\n    at Immediate.<anonymous> (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/common/connection.js:292:13)\n    at processImmediate (node:internal/timers:466:21) {\n  code: -32601,\n  data: undefined\n}\n"
[ERROR][2022-05-25 16:59:05] .../vim/lsp/rpc.lua:430	"rpc"	"unofficial-grammarly-language-server"	"stderr"	"1653487145712 ERROR  [GrammarlyAuth] Failed to get container ID\n"
[ERROR][2022-05-25 16:59:05] .../vim/lsp/rpc.lua:430	"rpc"	"unofficial-grammarly-language-server"	"stderr"	"/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:149\n        throw new Error('Authentication cannot be started.');\n              ^\n\nError: Authentication cannot be started.\n    at Object.anonymous (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:149:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async GrammarlyHostFactory.asAnonymous (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:662:29)\n    at async GrammarlyClient.getToken [as _getToken] (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:438:29)\n    at async GrammarlyClient._connect (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:419:25)\n"
```
